//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4952
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueBrick.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueBrick.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paint an Area.
        /// </summary>
        internal static string ActionAddArea {
            get {
                return ResourceManager.GetString("ActionAddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add part &amp;.
        /// </summary>
        internal static string ActionAddBrick {
            get {
                return ResourceManager.GetString("ActionAddBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an Area Layer.
        /// </summary>
        internal static string ActionAddLayerArea {
            get {
                return ResourceManager.GetString("ActionAddLayerArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Brick Layer.
        /// </summary>
        internal static string ActionAddLayerBrick {
            get {
                return ResourceManager.GetString("ActionAddLayerBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Grid layer.
        /// </summary>
        internal static string ActionAddLayerGrid {
            get {
                return ResourceManager.GetString("ActionAddLayerGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Text Layer.
        /// </summary>
        internal static string ActionAddLayerText {
            get {
                return ResourceManager.GetString("ActionAddLayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new text.
        /// </summary>
        internal static string ActionAddText {
            get {
                return ResourceManager.GetString("ActionAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bring selected Bricks to Front.
        /// </summary>
        internal static string ActionBringBrickToFront {
            get {
                return ResourceManager.GetString("ActionBringBrickToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bring selected Texts to Front.
        /// </summary>
        internal static string ActionBringTextToFront {
            get {
                return ResourceManager.GetString("ActionBringTextToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the background color.
        /// </summary>
        internal static string ActionChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ActionChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Map General Info.
        /// </summary>
        internal static string ActionChangeGeneralInfo {
            get {
                return ResourceManager.GetString("ActionChangeGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change map appearance.
        /// </summary>
        internal static string ActionChangeMapAppearance {
            get {
                return ResourceManager.GetString("ActionChangeMapAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erase an Area.
        /// </summary>
        internal static string ActionDeleteArea {
            get {
                return ResourceManager.GetString("ActionDeleteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete part &amp;.
        /// </summary>
        internal static string ActionDeleteBrick {
            get {
                return ResourceManager.GetString("ActionDeleteBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete several parts.
        /// </summary>
        internal static string ActionDeleteSeveralBricks {
            get {
                return ResourceManager.GetString("ActionDeleteSeveralBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete several texts.
        /// </summary>
        internal static string ActionDeleteSeveralTexts {
            get {
                return ResourceManager.GetString("ActionDeleteSeveralTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the text &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionDeleteText {
            get {
                return ResourceManager.GetString("ActionDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate the part &amp;.
        /// </summary>
        internal static string ActionDuplicateBrick {
            get {
                return ResourceManager.GetString("ActionDuplicateBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate several parts.
        /// </summary>
        internal static string ActionDuplicateSeveralBricks {
            get {
                return ResourceManager.GetString("ActionDuplicateSeveralBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate several texts.
        /// </summary>
        internal static string ActionDuplicateSeveralTexts {
            get {
                return ResourceManager.GetString("ActionDuplicateSeveralTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate the text &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionDuplicateText {
            get {
                return ResourceManager.GetString("ActionDuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit the text &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionEditText {
            get {
                return ResourceManager.GetString("ActionEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Flexible Bricks.
        /// </summary>
        internal static string ActionFlexMove {
            get {
                return ResourceManager.GetString("ActionFlexMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group Items.
        /// </summary>
        internal static string ActionGroupItems {
            get {
                return ResourceManager.GetString("ActionGroupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide the layer &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionHideLayer {
            get {
                return ResourceManager.GetString("ActionHideLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the Areas.
        /// </summary>
        internal static string ActionMoveArea {
            get {
                return ResourceManager.GetString("ActionMoveArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the part &amp;.
        /// </summary>
        internal static string ActionMoveBrick {
            get {
                return ResourceManager.GetString("ActionMoveBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the grid origin.
        /// </summary>
        internal static string ActionMoveGridOrigin {
            get {
                return ResourceManager.GetString("ActionMoveGridOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the layer &quot;&amp;&quot; Down.
        /// </summary>
        internal static string ActionMoveLayerDown {
            get {
                return ResourceManager.GetString("ActionMoveLayerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the layer &quot;&amp;&quot; Up.
        /// </summary>
        internal static string ActionMoveLayerUp {
            get {
                return ResourceManager.GetString("ActionMoveLayerUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move several parts.
        /// </summary>
        internal static string ActionMoveSeveralBricks {
            get {
                return ResourceManager.GetString("ActionMoveSeveralBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move several texts.
        /// </summary>
        internal static string ActionMoveSeveralTexts {
            get {
                return ResourceManager.GetString("ActionMoveSeveralTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move the text &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionMoveText {
            get {
                return ResourceManager.GetString("ActionMoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the layer &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionRemoveLayer {
            get {
                return ResourceManager.GetString("ActionRemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace the part &amp;.
        /// </summary>
        internal static string ActionReplaceBrick {
            get {
                return ResourceManager.GetString("ActionReplaceBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate the part &amp;.
        /// </summary>
        internal static string ActionRotateBrick {
            get {
                return ResourceManager.GetString("ActionRotateBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate several parts.
        /// </summary>
        internal static string ActionRotateSeveralBricks {
            get {
                return ResourceManager.GetString("ActionRotateSeveralBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate several texts.
        /// </summary>
        internal static string ActionRotateSeveralTexts {
            get {
                return ResourceManager.GetString("ActionRotateSeveralTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate the text &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionRotateText {
            get {
                return ResourceManager.GetString("ActionRotateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select layer &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionSelectLayer {
            get {
                return ResourceManager.GetString("ActionSelectLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send selected Bricks to Back.
        /// </summary>
        internal static string ActionSendBrickToBack {
            get {
                return ResourceManager.GetString("ActionSendBrickToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send selected Texts to Back.
        /// </summary>
        internal static string ActionSendTextToBack {
            get {
                return ResourceManager.GetString("ActionSendTextToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show layer &quot;&amp;&quot;.
        /// </summary>
        internal static string ActionShowLayer {
            get {
                return ResourceManager.GetString("ActionShowLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ungroup Items.
        /// </summary>
        internal static string ActionUngroupItems {
            get {
                return ResourceManager.GetString("ActionUngroupItems", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap aligncentered {
            get {
                object obj = ResourceManager.GetObject("aligncentered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignleft {
            get {
                object obj = ResourceManager.GetObject("alignleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignright {
            get {
                object obj = ResourceManager.GetObject("alignright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the options of layer &quot;&amp;&quot;.
        /// </summary>
        internal static string ChangeLayerOption {
            get {
                return ResourceManager.GetString("ChangeLayerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue Print.
        /// </summary>
        internal static string ColorSchemeBluePrint {
            get {
                return ResourceManager.GetString("ColorSchemeBluePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classic (printer friendly).
        /// </summary>
        internal static string ColorSchemeClassic {
            get {
                return ResourceManager.GetString("ColorSchemeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string ColorSchemeCustom {
            get {
                return ResourceManager.GetString("ColorSchemeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parchment.
        /// </summary>
        internal static string ColorSchemeParchment {
            get {
                return ResourceManager.GetString("ColorSchemeParchment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown Author.
        /// </summary>
        internal static string DefaultAuthor {
            get {
                return ResourceManager.GetString("DefaultAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer.
        /// </summary>
        internal static string DefaultLayerName {
            get {
                return ResourceManager.GetString("DefaultLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown LUG.
        /// </summary>
        internal static string DefaultLUG {
            get {
                return ResourceManager.GetString("DefaultLUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Untitled.bbm.
        /// </summary>
        internal static string DefaultSaveFileName {
            get {
                return ResourceManager.GetString("DefaultSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown Event.
        /// </summary>
        internal static string DefaultShow {
            get {
                return ResourceManager.GetString("DefaultShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have modified some default appearance settings. These settings will be used when you create new maps, but do you want to also apply these settings to your current map?.
        /// </summary>
        internal static string ErrorMsgApplyNewSettingsToAllLayers {
            get {
                return ResourceManager.GetString("ErrorMsgApplyNewSettingsToAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BlueBrick had encountered problems while loading images from the parts database. These images have been ignored. This problem may happen if an image is corrupted or too big. Remove the image(s) from your database to remove this warning. The image(s) concerned is/are: .
        /// </summary>
        internal static string ErrorMsgCanNotLoadImage {
            get {
                return ResourceManager.GetString("ErrorMsgCanNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BlueBrick had encountered problems while loading XML files from the parts database. These XML files have been ignored. This problem may happen if an XML file contains syntax errors. Fix the syntax or delete the XML files to remove this warning. The file(s) concerned is/are:.
        /// </summary>
        internal static string ErrorMsgCanNotLoadPartXML {
            get {
                return ResourceManager.GetString("ErrorMsgCanNotLoadPartXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot open the map &amp;..
        /// </summary>
        internal static string ErrorMsgCannotOpenMap {
            get {
                return ResourceManager.GetString("ErrorMsgCannotOpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not paste items of type &amp; in the current selected layer which is of type &amp;&amp;..
        /// </summary>
        internal static string ErrorMsgCanNotPaste {
            get {
                return ResourceManager.GetString("ErrorMsgCanNotPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot save the map &amp;..
        /// </summary>
        internal static string ErrorMsgCannotSaveMap {
            get {
                return ResourceManager.GetString("ErrorMsgCannotSaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to restore the default settings?.
        /// </summary>
        internal static string ErrorMsgConfirmRestoreDefault {
            get {
                return ResourceManager.GetString("ErrorMsgConfirmRestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BlueBrick Copyright (C) 2008 Alban NANTY. This program is free software under the GPLv3 license and comes with ABSOLUTELY NO WARRANTY. This program encountered a fatal error and will close. Please report this error to banban@lswproject.com. The error message is:.
        /// </summary>
        internal static string ErrorMsgCrash {
            get {
                return ResourceManager.GetString("ErrorMsgCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You changed the language but this will not take effect until you restart the application. Do you want to restart now?.
        /// </summary>
        internal static string ErrorMsgLanguageHasChanged {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Area.
        /// </summary>
        internal static string ErrorMsgLayerTypeArea {
            get {
                return ResourceManager.GetString("ErrorMsgLayerTypeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brick.
        /// </summary>
        internal static string ErrorMsgLayerTypeBrick {
            get {
                return ResourceManager.GetString("ErrorMsgLayerTypeBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid.
        /// </summary>
        internal static string ErrorMsgLayerTypeGrid {
            get {
                return ResourceManager.GetString("ErrorMsgLayerTypeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string ErrorMsgLayerTypeText {
            get {
                return ResourceManager.GetString("ErrorMsgLayerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your current map is not saved. Do you want to save your modification?.
        /// </summary>
        internal static string ErrorMsgMapWasModified {
            get {
                return ResourceManager.GetString("ErrorMsgMapWasModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not open the &quot;&amp;&quot; file. Without this file you will not be able to see the color and description of the parts in the part list. Please verify the presence of this file, or reinstall BlueBrick to fix the problem..
        /// </summary>
        internal static string ErrorMsgMissingColorInfoFile {
            get {
                return ResourceManager.GetString("ErrorMsgMissingColorInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not open the &quot;&amp;&quot; file. Without this file you will not be able to connect the parts together. Please verify the presence of this file, or reinstall BlueBrick to fix the problem..
        /// </summary>
        internal static string ErrorMsgMissingConnectionTypeInfoFile {
            get {
                return ResourceManager.GetString("ErrorMsgMissingConnectionTypeInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some parts were not correctly loaded because you don&apos;t have them in your parts library. Some default images have been temporarily added to replace the original ones. You should ask the map&apos;s author (&amp;) where you can find them..
        /// </summary>
        internal static string ErrorMsgMissingParts {
            get {
                return ResourceManager.GetString("ErrorMsgMissingParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some Track Designer part ID&apos;s were not found in your BlueBrick library. BlueBrick was not able to load them and has ignored them. You should ensure that you have the corresponding part in your BlueBrick library with the correct Track Designer ID set in the XML file and then try to re-open the Track Designer file. The missing ID&apos;s were:.
        /// </summary>
        internal static string ErrorMsgMissingTDRemap {
            get {
                return ResourceManager.GetString("ErrorMsgMissingTDRemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BlueBrick can not find the help file named &quot;BlueBrick.chm&quot; which is supposed to be in the installation folder. Reinstalling BlueBrick may fix the problem..
        /// </summary>
        internal static string ErrorMsgNoHelpFile {
            get {
                return ResourceManager.GetString("ErrorMsgNoHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format you have selected can not save all the data contained in your Layout. Grid, Area and Text information will be lost. Only the native BBM format can save all the data. Do you want to continue anyway?.
        /// </summary>
        internal static string ErrorMsgNotSavingInBBM {
            get {
                return ResourceManager.GetString("ErrorMsgNotSavingInBBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, the Track Designer file you are trying to load has an old version format. To fix this problem, open this file with Track Designer, and save it again. Now you should be able to load it with BlueBrick..
        /// </summary>
        internal static string ErrorMsgOldTDFile {
            get {
                return ResourceManager.GetString("ErrorMsgOldTDFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot load this file. Your version of BlueBrick is obsolete or the file may not be a valid BlueBrick file. Try downloading and installing the latest version of BlueBrick..
        /// </summary>
        internal static string ErrorMsgProgramObsolete {
            get {
                return ResourceManager.GetString("ErrorMsgProgramObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The parts library was unloaded, you can now modify the files in it. Click ok when you are ready to reload it..
        /// </summary>
        internal static string ErrorMsgReadyToReloadPartLib {
            get {
                return ResourceManager.GetString("ErrorMsgReadyToReloadPartLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorMsgTitleError {
            get {
                return ResourceManager.GetString("ErrorMsgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string ErrorMsgTitleWarning {
            get {
                return ResourceManager.GetString("ErrorMsgTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chineese.
        /// </summary>
        internal static string LanguageChineese {
            get {
                return ResourceManager.GetString("LanguageChineese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nederlands.
        /// </summary>
        internal static string LanguageDutch {
            get {
                return ResourceManager.GetString("LanguageDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English (default).
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsch.
        /// </summary>
        internal static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italiano.
        /// </summary>
        internal static string LanguageItalian {
            get {
                return ResourceManager.GetString("LanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Português.
        /// </summary>
        internal static string LanguagePortuguese {
            get {
                return ResourceManager.GetString("LanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap layerTypeArea {
            get {
                object obj = ResourceManager.GetObject("layerTypeArea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layerTypeBrick {
            get {
                object obj = ResourceManager.GetObject("layerTypeBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layerTypeGrid {
            get {
                object obj = ResourceManager.GetObject("layerTypeGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layerTypeText {
            get {
                object obj = ResourceManager.GetObject("layerTypeText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartForOptionPreview {
            get {
                object obj = ResourceManager.GetObject("PartForOptionPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bubble Information.
        /// </summary>
        internal static string PartLibMenuItemDisplayTooltips {
            get {
                return ResourceManager.GetString("PartLibMenuItemDisplayTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Large Icons.
        /// </summary>
        internal static string PartLibMenuItemLargeIcons {
            get {
                return ResourceManager.GetString("PartLibMenuItemLargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Respect Proportion.
        /// </summary>
        internal static string PartLibMenuItemRespectProportion {
            get {
                return ResourceManager.GetString("PartLibMenuItemRespectProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SnapGridOff {
            get {
                object obj = ResourceManager.GetObject("SnapGridOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SnapGridOn {
            get {
                object obj = ResourceManager.GetObject("SnapGridOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type your text here....
        /// </summary>
        internal static string TextEnterText {
            get {
                return ResourceManager.GetString("TextEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N/A.
        /// </summary>
        internal static string TextNA {
            get {
                return ResourceManager.GetString("TextNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string TextUnknown {
            get {
                return ResourceManager.GetString("TextUnknown", resourceCulture);
            }
        }
    }
}
