//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueBrick.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.002")]
        public double WheelMouseZoomSpeed {
            get {
                return ((double)(this["WheelMouseZoomSpeed"]));
            }
            set {
                this["WheelMouseZoomSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelMouseIsZoomOnCursor {
            get {
                return ((bool)(this["WheelMouseIsZoomOnCursor"]));
            }
            set {
                this["WheelMouseIsZoomOnCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UndoStackDepth {
            get {
                return ((int)(this["UndoStackDepth"]));
            }
            set {
                this["UndoStackDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultGridColor"]));
            }
            set {
                this["DefaultGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color DefaultBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBackgroundColor"]));
            }
            set {
                this["DefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt")]
        public global::System.Drawing.Font DefaultTextFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultTextFont"]));
            }
            set {
                this["DefaultTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultTextColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultTextColor"]));
            }
            set {
                this["DefaultTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color DefaultSubGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSubGridColor"]));
            }
            set {
                this["DefaultSubGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UndoStackDisplayedDepth {
            get {
                return ((int)(this["UndoStackDisplayedDepth"]));
            }
            set {
                this["UndoStackDisplayedDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseMultipleSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseMultipleSelectionKey"]));
            }
            set {
                this["MouseMultipleSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseZoomPanKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseZoomPanKey"]));
            }
            set {
                this["MouseZoomPanKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int DefaultGridSize {
            get {
                return ((int)(this["DefaultGridSize"]));
            }
            set {
                this["DefaultGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultSubDivisionNumber {
            get {
                return ((int)(this["DefaultSubDivisionNumber"]));
            }
            set {
                this["DefaultSubDivisionNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int DefaultAreaSize {
            get {
                return ((int)(this["DefaultAreaSize"]));
            }
            set {
                this["DefaultAreaSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DefaultAreaTransparency {
            get {
                return ((int)(this["DefaultAreaTransparency"]));
            }
            set {
                this["DefaultAreaTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayFreeConnexionPoints {
            get {
                return ((bool)(this["DisplayFreeConnexionPoints"]));
            }
            set {
                this["DisplayFreeConnexionPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartSavedMipmapLevel {
            get {
                return ((int)(this["StartSavedMipmapLevel"]));
            }
            set {
                this["StartSavedMipmapLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>65|1||</string>
  <string>72|1||</string>
  <string>67|4||</string>
  <string>68|5||</string>
  <string>69|6||</string>
  <string>70|7||</string>
  <string>36|3||</string>
  <string>51|3||</string>
  <string>37|2||</string>
  <string>66|8||</string>
  <string>76|9||</string>
  <string>75|10||</string>
  <string>23|0|32087.8|0</string>
  <string>18|0|2865.8|0</string>
  <string>11|0|2867.8|1</string>
  <string>17|0|2867.8|0</string>
  <string>24|0|2861.8|0</string>
  <string>10|0|2859.8|0</string>
  <string>5|0|FLEX.GROUP|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShortcutKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShortcutKey"]));
            }
            set {
                this["ShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseDuplicateSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseDuplicateSelectionKey"]));
            }
            set {
                this["MouseDuplicateSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxRecentFilesNum {
            get {
                return ((int)(this["MaxRecentFilesNum"]));
            }
            set {
                this["MaxRecentFilesNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33")]
        public float GammaForSelection {
            get {
                return ((float)(this["GammaForSelection"]));
            }
            set {
                this["GammaForSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public float GammaForSnappingPart {
            get {
                return ((float)(this["GammaForSnappingPart"]));
            }
            set {
                this["GammaForSnappingPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UIMainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UIMainFormLocation"]));
            }
            set {
                this["UIMainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("648, 545")]
        public global::System.Drawing.Size UIMainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["UIMainFormSize"]));
            }
            set {
                this["UIMainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState UIMainFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["UIMainFormWindowState"]));
            }
            set {
                this["UIMainFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UISnapGridEnabled {
            get {
                return ((bool)(this["UISnapGridEnabled"]));
            }
            set {
                this["UISnapGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float UISnapGridSize {
            get {
                return ((float)(this["UISnapGridSize"]));
            }
            set {
                this["UISnapGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public float UIRotationStep {
            get {
                return ((float)(this["UIRotationStep"]));
            }
            set {
                this["UIRotationStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIToolbarIsVisible {
            get {
                return ((bool)(this["UIToolbarIsVisible"]));
            }
            set {
                this["UIToolbarIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIStatusbarIsVisible {
            get {
                return ((bool)(this["UIStatusbarIsVisible"]));
            }
            set {
                this["UIStatusbarIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color UIPaintColor {
            get {
                return ((global::System.Drawing.Color)(this["UIPaintColor"]));
            }
            set {
                this["UIPaintColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIIsEraserToolSelected {
            get {
                return ((bool)(this["UIIsEraserToolSelected"]));
            }
            set {
                this["UIIsEraserToolSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int UIMainSplitContainerDistance {
            get {
                return ((int)(this["UIMainSplitContainerDistance"]));
            }
            set {
                this["UIMainSplitContainerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int UIToolSplitContainerDistance {
            get {
                return ((int)(this["UIToolSplitContainerDistance"]));
            }
            set {
                this["UIToolSplitContainerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Baseplate</string>
  <string>Road</string>
  <string>Track</string>
  <string>Train</string>
  <string>Town</string>
  <string>Space</string>
  <string>Table</string>
  <string>Custom</string>
  <string>Logo</string>
  <string>Duplo</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PartLibTabOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PartLibTabOrder"]));
            }
            set {
                this["PartLibTabOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PartLibBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PartLibBackColor"]));
            }
            set {
                this["PartLibBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibDisplayBubbleInfo {
            get {
                return ((bool)(this["PartLibDisplayBubbleInfo"]));
            }
            set {
                this["PartLibDisplayBubbleInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartLibBubbleInfoPartID {
            get {
                return ((bool)(this["PartLibBubbleInfoPartID"]));
            }
            set {
                this["PartLibBubbleInfoPartID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartLibBubbleInfoPartColor {
            get {
                return ((bool)(this["PartLibBubbleInfoPartColor"]));
            }
            set {
                this["PartLibBubbleInfoPartColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartLibBubbleInfoPartDescription {
            get {
                return ((bool)(this["PartLibBubbleInfoPartDescription"]));
            }
            set {
                this["PartLibBubbleInfoPartDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Baseplate11</string>
  <string>Road11</string>
  <string>Track10</string>
  <string>Train Set11</string>
  <string>Town10</string>
  <string>Train10</string>
  <string>Space10</string>
  <string>Castle10</string>
  <string>Table10</string>
  <string>Custom10</string>
  <string>Logo10</string>
  <string>Duplo10</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPartLibDisplayConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPartLibDisplayConfig"]));
            }
            set {
                this["UIPartLibDisplayConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayGeneralInfoWatermark {
            get {
                return ((bool)(this["DisplayGeneralInfoWatermark"]));
            }
            set {
                this["DisplayGeneralInfoWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayElectricCircuit {
            get {
                return ((bool)(this["DisplayElectricCircuit"]));
            }
            set {
                this["DisplayElectricCircuit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultGridEnabled {
            get {
                return ((bool)(this["DefaultGridEnabled"]));
            }
            set {
                this["DefaultGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultSubGridEnabled {
            get {
                return ((bool)(this["DefaultSubGridEnabled"]));
            }
            set {
                this["DefaultSubGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public double UIViewScale {
            get {
                return ((double)(this["UIViewScale"]));
            }
            set {
                this["UIViewScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color PartLibFilteredBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PartLibFilteredBackColor"]));
            }
            set {
                this["PartLibFilteredBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UIPartLibSelectedTabIndex {
            get {
                return ((int)(this["UIPartLibSelectedTabIndex"]));
            }
            set {
                this["UIPartLibSelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UIRulerToolSelected {
            get {
                return ((int)(this["UIRulerToolSelected"]));
            }
            set {
                this["UIRulerToolSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayBrickHull {
            get {
                return ((bool)(this["DisplayBrickHull"]));
            }
            set {
                this["DisplayBrickHull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int OffsetAfterCopyStyle {
            get {
                return ((int)(this["OffsetAfterCopyStyle"]));
            }
            set {
                this["OffsetAfterCopyStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float OffsetAfterCopyValue {
            get {
                return ((float)(this["OffsetAfterCopyValue"]));
            }
            set {
                this["OffsetAfterCopyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForNotSavingInBBM {
            get {
                return ((bool)(this["DisplayWarningMessageForNotSavingInBBM"]));
            }
            set {
                this["DisplayWarningMessageForNotSavingInBBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RulerControlPointRadiusInPixel {
            get {
                return ((int)(this["RulerControlPointRadiusInPixel"]));
            }
            set {
                this["RulerControlPointRadiusInPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayRulerAttachPoints {
            get {
                return ((bool)(this["DisplayRulerAttachPoints"]));
            }
            set {
                this["DisplayRulerAttachPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchToEditionAfterRulerCreation {
            get {
                return ((bool)(this["SwitchToEditionAfterRulerCreation"]));
            }
            set {
                this["SwitchToEditionAfterRulerCreation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float RulerDefaultLineThickness {
            get {
                return ((float)(this["RulerDefaultLineThickness"]));
            }
            set {
                this["RulerDefaultLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RulerDefaultLineColor {
            get {
                return ((global::System.Drawing.Color)(this["RulerDefaultLineColor"]));
            }
            set {
                this["RulerDefaultLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RulerDefaultAllowOffset {
            get {
                return ((bool)(this["RulerDefaultAllowOffset"]));
            }
            set {
                this["RulerDefaultAllowOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float RulerDefaultDashPatternLine {
            get {
                return ((float)(this["RulerDefaultDashPatternLine"]));
            }
            set {
                this["RulerDefaultDashPatternLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float RulerDefaultDashPatternSpace {
            get {
                return ((float)(this["RulerDefaultDashPatternSpace"]));
            }
            set {
                this["RulerDefaultDashPatternSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float RulerDefaultGuidelineThickness {
            get {
                return ((float)(this["RulerDefaultGuidelineThickness"]));
            }
            set {
                this["RulerDefaultGuidelineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RulerDefaultGuidelineColor {
            get {
                return ((global::System.Drawing.Color)(this["RulerDefaultGuidelineColor"]));
            }
            set {
                this["RulerDefaultGuidelineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RulerDefaultDisplayUnit {
            get {
                return ((bool)(this["RulerDefaultDisplayUnit"]));
            }
            set {
                this["RulerDefaultDisplayUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RulerDefaultDisplayMeasureText {
            get {
                return ((bool)(this["RulerDefaultDisplayMeasureText"]));
            }
            set {
                this["RulerDefaultDisplayMeasureText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RulerDefaultUnit {
            get {
                return ((int)(this["RulerDefaultUnit"]));
            }
            set {
                this["RulerDefaultUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RulerDefaultFontColor {
            get {
                return ((global::System.Drawing.Color)(this["RulerDefaultFontColor"]));
            }
            set {
                this["RulerDefaultFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 15.75pt")]
        public global::System.Drawing.Font RulerDefaultFont {
            get {
                return ((global::System.Drawing.Font)(this["RulerDefaultFont"]));
            }
            set {
                this["RulerDefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIFilterAllLibraryTab {
            get {
                return ((bool)(this["UIFilterAllLibraryTab"]));
            }
            set {
                this["UIFilterAllLibraryTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UIFilterAllSentence {
            get {
                return ((string)(this["UIFilterAllSentence"]));
            }
            set {
                this["UIFilterAllSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayOtherHull {
            get {
                return ((bool)(this["DisplayOtherHull"]));
            }
            set {
                this["DisplayOtherHull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BrickHullColor {
            get {
                return ((global::System.Drawing.Color)(this["BrickHullColor"]));
            }
            set {
                this["BrickHullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color OtherHullColor {
            get {
                return ((global::System.Drawing.Color)(this["OtherHullColor"]));
            }
            set {
                this["OtherHullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Narrow, 9.75pt")]
        public global::System.Drawing.Font WatermarkFont {
            get {
                return ((global::System.Drawing.Font)(this["WatermarkFont"]));
            }
            set {
                this["WatermarkFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119, 255, 255, 255")]
        public global::System.Drawing.Color WatermarkBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["WatermarkBackgroundColor"]));
            }
            set {
                this["WatermarkBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WatermarkColor {
            get {
                return ((global::System.Drawing.Color)(this["WatermarkColor"]));
            }
            set {
                this["WatermarkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIExportWatermark {
            get {
                return ((bool)(this["UIExportWatermark"]));
            }
            set {
                this["UIExportWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIExportHulls {
            get {
                return ((bool)(this["UIExportHulls"]));
            }
            set {
                this["UIExportHulls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIExportElectricCircuit {
            get {
                return ((bool)(this["UIExportElectricCircuit"]));
            }
            set {
                this["UIExportElectricCircuit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIExportConnection {
            get {
                return ((bool)(this["UIExportConnection"]));
            }
            set {
                this["UIExportConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBudgetNumbers {
            get {
                return ((bool)(this["ShowBudgetNumbers"]));
            }
            set {
                this["ShowBudgetNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBudgetLimitation {
            get {
                return ((bool)(this["UseBudgetLimitation"]));
            }
            set {
                this["UseBudgetLimitation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDefaultBudgetInfinite {
            get {
                return ((bool)(this["IsDefaultBudgetInfinite"]));
            }
            set {
                this["IsDefaultBudgetInfinite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnlyBudgetedParts {
            get {
                return ((bool)(this["ShowOnlyBudgetedParts"]));
            }
            set {
                this["ShowOnlyBudgetedParts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LemonChiffon")]
        public global::System.Drawing.Color PartLibShowOnlyBudgetedPartsColor {
            get {
                return ((global::System.Drawing.Color)(this["PartLibShowOnlyBudgetedPartsColor"]));
            }
            set {
                this["PartLibShowOnlyBudgetedPartsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForBrickNotCopiedDueToBudgetLimitation {
            get {
                return ((bool)(this["DisplayWarningMessageForBrickNotCopiedDueToBudgetLimitation"]));
            }
            set {
                this["DisplayWarningMessageForBrickNotCopiedDueToBudgetLimitation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BudgetFilenameToLoadAtStartup {
            get {
                return ((string)(this["BudgetFilenameToLoadAtStartup"]));
            }
            set {
                this["BudgetFilenameToLoadAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForShowingBudgetNumbers {
            get {
                return ((bool)(this["DisplayWarningMessageForShowingBudgetNumbers"]));
            }
            set {
                this["DisplayWarningMessageForShowingBudgetNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForBrickNotAddedDueToBudgetLimitation {
            get {
                return ((bool)(this["DisplayWarningMessageForBrickNotAddedDueToBudgetLimitation"]));
            }
            set {
                this["DisplayWarningMessageForBrickNotAddedDueToBudgetLimitation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForBrickNotReplacedDueToBudgetLimitation {
            get {
                return ((bool)(this["DisplayWarningMessageForBrickNotReplacedDueToBudgetLimitation"]));
            }
            set {
                this["DisplayWarningMessageForBrickNotReplacedDueToBudgetLimitation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayRemainingPartCountInBudgetInsteadOfUsedCount {
            get {
                return ((bool)(this["DisplayRemainingPartCountInBudgetInsteadOfUsedCount"]));
            }
            set {
                this["DisplayRemainingPartCountInBudgetInsteadOfUsedCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibDisplayPartInfo {
            get {
                return ((bool)(this["PartLibDisplayPartInfo"]));
            }
            set {
                this["PartLibDisplayPartInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartLibPartInfoPartDescription {
            get {
                return ((bool)(this["PartLibPartInfoPartDescription"]));
            }
            set {
                this["PartLibPartInfoPartDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibPartInfoPartColor {
            get {
                return ((bool)(this["PartLibPartInfoPartColor"]));
            }
            set {
                this["PartLibPartInfoPartColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibPartInfoPartID {
            get {
                return ((bool)(this["PartLibPartInfoPartID"]));
            }
            set {
                this["PartLibPartInfoPartID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UISplitPartUsagePerLayer {
            get {
                return ((bool)(this["UISplitPartUsagePerLayer"]));
            }
            set {
                this["UISplitPartUsagePerLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIIncludeHiddenPartsInPartUsage {
            get {
                return ((bool)(this["UIIncludeHiddenPartsInPartUsage"]));
            }
            set {
                this["UIIncludeHiddenPartsInPartUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayWarningMessageForPastingOnWrongLayer {
            get {
                return ((bool)(this["DisplayWarningMessageForPastingOnWrongLayer"]));
            }
            set {
                this["DisplayWarningMessageForPastingOnWrongLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float BrickHullThickness {
            get {
                return ((float)(this["BrickHullThickness"]));
            }
            set {
                this["BrickHullThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float OtherHullThickness {
            get {
                return ((float)(this["OtherHullThickness"]));
            }
            set {
                this["OtherHullThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config/ClassicTemplate.bbm")]
        public string TemplateFilenameWhenCreatingANewMap {
            get {
                return ((string)(this["TemplateFilenameWhenCreatingANewMap"]));
            }
            set {
                this["TemplateFilenameWhenCreatingANewMap"] = value;
            }
        }
    }
}
