//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueBrick.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.002")]
        public double WheelMouseZoomSpeed {
            get {
                return ((double)(this["WheelMouseZoomSpeed"]));
            }
            set {
                this["WheelMouseZoomSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelMouseIsZoomOnCursor {
            get {
                return ((bool)(this["WheelMouseIsZoomOnCursor"]));
            }
            set {
                this["WheelMouseIsZoomOnCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddGridLayerOnNewMap {
            get {
                return ((bool)(this["AddGridLayerOnNewMap"]));
            }
            set {
                this["AddGridLayerOnNewMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddBrickLayerOnNewMap {
            get {
                return ((bool)(this["AddBrickLayerOnNewMap"]));
            }
            set {
                this["AddBrickLayerOnNewMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UndoStackDepth {
            get {
                return ((int)(this["UndoStackDepth"]));
            }
            set {
                this["UndoStackDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultGridColor"]));
            }
            set {
                this["DefaultGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color DefaultBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBackgroundColor"]));
            }
            set {
                this["DefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt")]
        public global::System.Drawing.Font DefaultTextFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultTextFont"]));
            }
            set {
                this["DefaultTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultTextColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultTextColor"]));
            }
            set {
                this["DefaultTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color DefaultSubGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSubGridColor"]));
            }
            set {
                this["DefaultSubGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultLUG {
            get {
                return ((string)(this["DefaultLUG"]));
            }
            set {
                this["DefaultLUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultShow {
            get {
                return ((string)(this["DefaultShow"]));
            }
            set {
                this["DefaultShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultAuthor {
            get {
                return ((string)(this["DefaultAuthor"]));
            }
            set {
                this["DefaultAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UndoStackDisplayedDepth {
            get {
                return ((int)(this["UndoStackDisplayedDepth"]));
            }
            set {
                this["UndoStackDisplayedDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+None")]
        public global::System.Windows.Forms.Keys MouseMultipleSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseMultipleSelectionKey"]));
            }
            set {
                this["MouseMultipleSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+None")]
        public global::System.Windows.Forms.Keys MouseZoomKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseZoomKey"]));
            }
            set {
                this["MouseZoomKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+Shift+None")]
        public global::System.Windows.Forms.Keys MousePanKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MousePanKey"]));
            }
            set {
                this["MousePanKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int DefaultGridSize {
            get {
                return ((int)(this["DefaultGridSize"]));
            }
            set {
                this["DefaultGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultSubDivisionNumber {
            get {
                return ((int)(this["DefaultSubDivisionNumber"]));
            }
            set {
                this["DefaultSubDivisionNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int DefaultAreaSize {
            get {
                return ((int)(this["DefaultAreaSize"]));
            }
            set {
                this["DefaultAreaSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DefaultAreaTransparency {
            get {
                return ((int)(this["DefaultAreaTransparency"]));
            }
            set {
                this["DefaultAreaTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayFreeConnexionPoints {
            get {
                return ((bool)(this["DisplayFreeConnexionPoints"]));
            }
            set {
                this["DisplayFreeConnexionPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartSavedMipmapLevel {
            get {
                return ((int)(this["StartSavedMipmapLevel"]));
            }
            set {
                this["StartSavedMipmapLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>65|1||</string>
  <string>72|1||</string>
  <string>67|4||</string>
  <string>68|5||</string>
  <string>69|6||</string>
  <string>70|7||</string>
  <string>36|3||</string>
  <string>51|3||</string>
  <string>37|2||</string>
  <string>66|8||</string>
  <string>23|0|32087.8|0</string>
  <string>18|0|2865.8|0</string>
  <string>11|0|2867.8|0</string>
  <string>17|0|2867.8|1</string>
  <string>24|0|2861.8|0</string>
  <string>10|0|2859.8|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShortcutKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShortcutKey"]));
            }
            set {
                this["ShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+None")]
        public global::System.Windows.Forms.Keys MouseDuplicateSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseDuplicateSelectionKey"]));
            }
            set {
                this["MouseDuplicateSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxRecentFilesNum {
            get {
                return ((int)(this["MaxRecentFilesNum"]));
            }
            set {
                this["MaxRecentFilesNum"] = value;
            }
        }
    }
}
