//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueBrick.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.002")]
        public double WheelMouseZoomSpeed {
            get {
                return ((double)(this["WheelMouseZoomSpeed"]));
            }
            set {
                this["WheelMouseZoomSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelMouseIsZoomOnCursor {
            get {
                return ((bool)(this["WheelMouseIsZoomOnCursor"]));
            }
            set {
                this["WheelMouseIsZoomOnCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddGridLayerOnNewMap {
            get {
                return ((bool)(this["AddGridLayerOnNewMap"]));
            }
            set {
                this["AddGridLayerOnNewMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddBrickLayerOnNewMap {
            get {
                return ((bool)(this["AddBrickLayerOnNewMap"]));
            }
            set {
                this["AddBrickLayerOnNewMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UndoStackDepth {
            get {
                return ((int)(this["UndoStackDepth"]));
            }
            set {
                this["UndoStackDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultGridColor"]));
            }
            set {
                this["DefaultGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color DefaultBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBackgroundColor"]));
            }
            set {
                this["DefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt")]
        public global::System.Drawing.Font DefaultTextFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultTextFont"]));
            }
            set {
                this["DefaultTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultTextColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultTextColor"]));
            }
            set {
                this["DefaultTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color DefaultSubGridColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSubGridColor"]));
            }
            set {
                this["DefaultSubGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultLUG {
            get {
                return ((string)(this["DefaultLUG"]));
            }
            set {
                this["DefaultLUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultShow {
            get {
                return ((string)(this["DefaultShow"]));
            }
            set {
                this["DefaultShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***NotInitialized***")]
        public string DefaultAuthor {
            get {
                return ((string)(this["DefaultAuthor"]));
            }
            set {
                this["DefaultAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UndoStackDisplayedDepth {
            get {
                return ((int)(this["UndoStackDisplayedDepth"]));
            }
            set {
                this["UndoStackDisplayedDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseMultipleSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseMultipleSelectionKey"]));
            }
            set {
                this["MouseMultipleSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseZoomPanKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseZoomPanKey"]));
            }
            set {
                this["MouseZoomPanKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int DefaultGridSize {
            get {
                return ((int)(this["DefaultGridSize"]));
            }
            set {
                this["DefaultGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultSubDivisionNumber {
            get {
                return ((int)(this["DefaultSubDivisionNumber"]));
            }
            set {
                this["DefaultSubDivisionNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int DefaultAreaSize {
            get {
                return ((int)(this["DefaultAreaSize"]));
            }
            set {
                this["DefaultAreaSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DefaultAreaTransparency {
            get {
                return ((int)(this["DefaultAreaTransparency"]));
            }
            set {
                this["DefaultAreaTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayFreeConnexionPoints {
            get {
                return ((bool)(this["DisplayFreeConnexionPoints"]));
            }
            set {
                this["DisplayFreeConnexionPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartSavedMipmapLevel {
            get {
                return ((int)(this["StartSavedMipmapLevel"]));
            }
            set {
                this["StartSavedMipmapLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>65|1||</string>
  <string>72|1||</string>
  <string>67|4||</string>
  <string>68|5||</string>
  <string>69|6||</string>
  <string>70|7||</string>
  <string>36|3||</string>
  <string>51|3||</string>
  <string>37|2||</string>
  <string>66|8||</string>
  <string>76|9||</string>
  <string>75|10||</string>
  <string>23|0|32087.8|0</string>
  <string>18|0|2865.8|0</string>
  <string>11|0|2867.8|1</string>
  <string>17|0|2867.8|0</string>
  <string>24|0|2861.8|0</string>
  <string>10|0|2859.8|0</string>
  <string>5|0|FLEX.GROUP|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShortcutKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShortcutKey"]));
            }
            set {
                this["ShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseDuplicateSelectionKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseDuplicateSelectionKey"]));
            }
            set {
                this["MouseDuplicateSelectionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxRecentFilesNum {
            get {
                return ((int)(this["MaxRecentFilesNum"]));
            }
            set {
                this["MaxRecentFilesNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33")]
        public float GammaForSelection {
            get {
                return ((float)(this["GammaForSelection"]));
            }
            set {
                this["GammaForSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public float GammaForSnappingPart {
            get {
                return ((float)(this["GammaForSnappingPart"]));
            }
            set {
                this["GammaForSnappingPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UIMainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UIMainFormLocation"]));
            }
            set {
                this["UIMainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("648, 545")]
        public global::System.Drawing.Size UIMainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["UIMainFormSize"]));
            }
            set {
                this["UIMainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState UIMainFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["UIMainFormWindowState"]));
            }
            set {
                this["UIMainFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UIPartListFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UIPartListFormLocation"]));
            }
            set {
                this["UIPartListFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState UIPartListFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["UIPartListFormWindowState"]));
            }
            set {
                this["UIPartListFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("446, 577")]
        public global::System.Drawing.Size UIPartListFormSize {
            get {
                return ((global::System.Drawing.Size)(this["UIPartListFormSize"]));
            }
            set {
                this["UIPartListFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UISnapGridEnabled {
            get {
                return ((bool)(this["UISnapGridEnabled"]));
            }
            set {
                this["UISnapGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float UISnapGridSize {
            get {
                return ((float)(this["UISnapGridSize"]));
            }
            set {
                this["UISnapGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public float UIRotationStep {
            get {
                return ((float)(this["UIRotationStep"]));
            }
            set {
                this["UIRotationStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UIPartListFormIsVisible {
            get {
                return ((bool)(this["UIPartListFormIsVisible"]));
            }
            set {
                this["UIPartListFormIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIToolbarIsVisible {
            get {
                return ((bool)(this["UIToolbarIsVisible"]));
            }
            set {
                this["UIToolbarIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIStatusbarIsVisible {
            get {
                return ((bool)(this["UIStatusbarIsVisible"]));
            }
            set {
                this["UIStatusbarIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color UIPaintColor {
            get {
                return ((global::System.Drawing.Color)(this["UIPaintColor"]));
            }
            set {
                this["UIPaintColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UIIsPaintToolSelected {
            get {
                return ((bool)(this["UIIsPaintToolSelected"]));
            }
            set {
                this["UIIsPaintToolSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int UIMainSplitContainerDistance {
            get {
                return ((int)(this["UIMainSplitContainerDistance"]));
            }
            set {
                this["UIMainSplitContainerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int UIToolSplitContainerDistance {
            get {
                return ((int)(this["UIToolSplitContainerDistance"]));
            }
            set {
                this["UIToolSplitContainerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Baseplate</string>
  <string>Road</string>
  <string>Track</string>
  <string>Train</string>
  <string>Town</string>
  <string>Space</string>
  <string>Table</string>
  <string>Custom</string>
  <string>Logo</string>
  <string>Duplo</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PartLibTabOrder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PartLibTabOrder"]));
            }
            set {
                this["PartLibTabOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PartLibBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PartLibBackColor"]));
            }
            set {
                this["PartLibBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibDisplayBubbleInfo {
            get {
                return ((bool)(this["PartLibDisplayBubbleInfo"]));
            }
            set {
                this["PartLibDisplayBubbleInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibBubbleInfoPartID {
            get {
                return ((bool)(this["PartLibBubbleInfoPartID"]));
            }
            set {
                this["PartLibBubbleInfoPartID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartLibBubbleInfoPartColor {
            get {
                return ((bool)(this["PartLibBubbleInfoPartColor"]));
            }
            set {
                this["PartLibBubbleInfoPartColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartLibBubbleInfoPartDescription {
            get {
                return ((bool)(this["PartLibBubbleInfoPartDescription"]));
            }
            set {
                this["PartLibBubbleInfoPartDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Baseplate11</string>
  <string>Road11</string>
  <string>Track10</string>
  <string>Train Set11</string>
  <string>Town10</string>
  <string>Train10</string>
  <string>Space10</string>
  <string>Castle10</string>
  <string>Table10</string>
  <string>Custom10</string>
  <string>Logo10</string>
  <string>Duplo10</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPartLibDisplayConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPartLibDisplayConfig"]));
            }
            set {
                this["UIPartLibDisplayConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayGeneralInfoWatermark {
            get {
                return ((bool)(this["DisplayGeneralInfoWatermark"]));
            }
            set {
                this["DisplayGeneralInfoWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayElectricCircuit {
            get {
                return ((bool)(this["DisplayElectricCircuit"]));
            }
            set {
                this["DisplayElectricCircuit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultGridEnabled {
            get {
                return ((bool)(this["DefaultGridEnabled"]));
            }
            set {
                this["DefaultGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultSubGridEnabled {
            get {
                return ((bool)(this["DefaultSubGridEnabled"]));
            }
            set {
                this["DefaultSubGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public double UIViewScale {
            get {
                return ((double)(this["UIViewScale"]));
            }
            set {
                this["UIViewScale"] = value;
            }
        }
    }
}
